name: geo_quest
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_osm_plugin: ^0.60.5
  pointer_interceptor: ^0.9.3+6
  open_route_service: ^1.2.3
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
